const RATE_LIMIT_CYCLE = process.env.RATE_LIMIT_CYCLE || 60 * 1000;
const RATE_LIMIT_MAX_PER_CYCLE = process.env.RATE_LIMIT_MAX_PER_CYCLE || 1000;

module.exports = {
  RATE_LIMIT_MAX_PER_CYCLE,
  RATE_LIMIT_CYCLE,
};
